name: Fix CS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)
            echo "Files changed: $FILES_CHANGED"
            git commit -m "Google Java Format" $FILES_CHANGED
          else
            git commit -m "Google Java Format" -a
          fi
          git push
