name: Check Style

on: [push, pull_request]

jobs:
  java-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Java Checkstyle
        uses: Justintime50/java-checkstyle-action@v1
        with:
          directory: /src
          
          style_suite: google
