name: Fix CS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git commit -m "Google Java Format" --author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>" -a
          git push
