name: Processing Problem Matcher

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: benthillerkus/processing-problem-matcher@master
    - name: Build Project
      run: processing-java --sketch={{ $github.workspace }} --build
